### ISSUE TITLE
Release 0.33.0

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/llvmlite-feedstock#31]
Normally an automated PR would be added to the feedstock to update to 0.33.0. However this hasn't happened as there is no `sdist` for llvmlite 0.33.0 on PyPI, which we [rely on]( https://github.com/conda-forge/llvmlite-feedstock/blob/4cf751b59e327f83f6f2df86ad63cb6b82a79bc7/recipe/meta.yaml#L12 ). Have opened issue ( https://github.com/numba/llvmlite/issues/595 ) upstream about getting an `sdist` for llvmlite 0.33.0.

**Comment by henryiii** [comment]
It’s always a little slow showing up.

**Comment by jakirkham** [comment]
The Numba team hasn't published it yet. So there is nothing for us to do until that happens.

**Comment by jakirkham** [comment]
Looks like they published it recently as the bot submitted PR ( https://github.com/conda-forge/llvmlite-feedstock/pull/32 ).
