### ISSUE TITLE
Windows + Python 3.8 failing

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/llvmlite-feedstock#35]
After considerable effort trying to get Windows builds to work, we were unable to get Windows + Python 3.8 builds to pass in `llvmlite` version `0.33.0` in PR ( https://github.com/conda-forge/llvmlite-feedstock/pull/32 ). It’s unclear why that issue is only coming up now (as previous releases didn’t have this issue) or why other Windows builds are unaffected. In any event this issue exists to track this problem. Any help others may be able to provide on this issue would be most welcome 🙂

**Comment by isuruf** [comment]
Try skipping the tests in the build phase so that you can see if there is any linking issue in the post-link phase by conda-build. conda-build will give warnings after analyzing dependencies.
