### ISSUE TITLE
False runtime dependency on libllvm9

### ISSUE THREAD

**Issue by pitrou** [conda-forge/llvmlite-feedstock#37]
The llvmlite package declares a runtime dependency on `libllvm9`. But this is not necessary, since llvmlite links statically with the required LLVM components (hence the large package size).
Indeed the `.so` file does not link to the LLVM shared libraries:
```
$ ldd .../llvmlite-0.33.0-py37hd408876_0/lib/python3.7/site-packages/llvmlite/binding/libllvmlite.so
	linux-vdso.so.1 (0x00007ffc0b198000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fef78e25000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fef78c06000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fef78868000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fef78650000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fef7825f000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fef7c7a3000)
```

**Comment by jakirkham** [comment]
We don’t statically link in conda-forge. We dynamically link.

**Comment by pitrou** [comment]
Well, look at the output above. It doesn't look dynamically linked with `libllvm.so` to me, and if it were then `libllvmlite.so` wouldn't be a 70 MB file (!).
Another piece of evidence:
```
$ nm --defined-only --demangle miniconda3/pkgs/llvmlite-0.33.0-py37hd408876_0/lib/python3.7/site-packages/llvmlite/binding/libllvmlite.so | grep "llvm::" | wc -l
61659
```
(replace `wc -l ` with `less` to view all the LLVM symbols statically linked into `libllvmlite.so`)

**Comment by jakirkham** [comment]
Can you please include details about the Conda environment where this package was installed?

Should note I’m on break atm. So probably won’t look into this personally for a bit

**Comment by pitrou** [comment]
> Can you please include details about the Conda environment where this package was installed?

I don't understand why you're asking this. Regardless of how the package is installed, it is still linked the same way, no?

**Comment by xhochy** [comment]
The linkage on OSX is correct, there `libllvmlite.dylib` is only 518K in size and dynamically linked to `@rpath/libLLVM-9.dylib`.

**Comment by xhochy** [comment]
@pitrou The package hash you are referring to is from `defaults`, not `conda-forge`: http://repo.continuum.io/pkgs/main/linux-64/llvmlite-0.33.0-py37hd408876_0.tar.bz2 Please open an issue over there (closing here as we cannot tranfer issues over there). `conda-forge` packages link dynamically but should depend on `libllvm` not `llvmdev`.
