### ISSUE TITLE
SVML issue with Windows

### ISSUE THREAD

**Issue by seibert** [conda-forge/llvmlite-feedstock#5]
An issue opened up on the Numba tracker:

https://github.com/numba/numba/issues/2998

Shows an issue on Windows with the llvmlite from conda-forge when the SVML support is enabled. 
 SVML support is enabled automatically when the library is detected, and on Windows, SVML is always present because ICC is used as the Fortran compiler.  Further testing by the user indicated that this bug is not present with Anaconda's build of llvmlite.

It appears that llvmdev is missing this patch:

https://github.com/numba/llvmlite/blob/master/conda-recipes/llvmdev/meta.yaml#L18

which is needed for the SVML feature to work correctly.

(Also cross posting this issue into llvmdev-feedstock tracker, as that will need to be rebuilt before llvmlite is.)

**Comment by jakirkham** [comment]
Thanks for the info. This appears to have been solved in PR ( https://github.com/conda-forge/llvmdev-feedstock/pull/53 ).
